### ISSUE TITLE
Return `null` on invalid uri

### ISSUE THREAD

**Issue by delvedor** [jridgewell/safe-decode-uri-component#1]
Hello!
Great library! I would like to use it in [delvedor/find-my-way](https://github.com/delvedor/find-my-way) in place of the native `decodeURIComponent`.
In my use case I need to return null on invalid uri instead of return the uri as you are doing here.
What do you think about change the API and accept an options object and let the user choose the behavior?

I can make a pr, let me know.
Thanks.

**Comment by thecotne** [comment]
use this

```js
function decodeURIComponent (uri) {
  try {
    return decodeURIComponent(uri)
  } catch (e) {
    return null
  }
}
```

**Comment by jridgewell** [comment]
Yah, a simple try-catch would be best for you:

```js
function decodeOrNull(uri) {
  try {
    return decodeURIComponent(uri);
  } catch (e) {
    return null;
  }
}
```
